#!/bin/sh

set -e

case $reason in
    BOUND6|RENEW6|REBIND6)
	;;
    *)
	exit 0
	;;
esac

i=0
for srv in $new_dhcp6_name_servers; do
	echo "nameserver[$i] $srv"
	i=$(($i+1))
done

i=0
for srv in $new_dhcp6_domain_search; do
	echo "Domain search list[$i] $srv"
	i=$(($i+1))
done

i=0
for srv in $new_dhcp6_sntp_servers; do
	echo "NTP server[$i] $srv"
	i=$(($i+1))
done

echo "end"
